import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/preview/DisableDraftMode";
import "./globals.css";
import "quirk-ui/styles.css";
// import { SanityLiveVisualEditing } from "@/components/preview/SanityLiveVisualEditing";

const roboto = Roboto_Flex({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ overflow: "visible", scrollBehavior: "smooth" }}>
      <body className={roboto.className}>
        {(await draftMode()).isEnabled && (
          <>
            {/* <SanityLiveVisualEditing /> */}
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
        {children}
      </body>
    </html>
  );
}
